---
security:
#password cf client will use when interacting with broker
  user.password: ${user.password}
yarn:
  #encoded hadoop configuration files for yarn
  provided.zip: ${hadoop.provided.zip:}
store:
  #optional parameter to configure zookeeper-store
  path: ${broker.store.znode:/broker/yarn/metadata}
  user: ${system.user}
  password: ${system.user.password}
cf:
  catalog:
    serviceName: ${cf.catalog.servicename:yarn}
    serviceId: ${cf.catalog.serviceid:yarn}
    serviceDescription: "YARN service allow to access resources on hadoop cluster."
    baseId: ${BASE_GUID:}
    plans:
      - id: bare-plan
        name: bare
        description: bare
        free: true
      - id: multitenant-plan
        name: multitenant
        description: multitenant
        free: true
    metadata:
      imageUrl: ${IMAGE_URL:}

